apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs-app.fullname" . }}
  labels:
    app: {{ include "nextjs-app.name" . }}
    chart: {{ include "nextjs-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nextjs-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "nextjs-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "nextjs-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
        {{ toYaml .Values.tolerations | indent 8 }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
