apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs-app.fullname" . }}-azure-ad-secrets
type: Opaque
stringData:
  AZURE_AD_CLIENT_ID: {{ .Values.secrets.azureAdClientId | quote }}
  AZURE_AD_CLIENT_SECRET: {{ .Values.secrets.azureAdClientSecret | quote }}
  AZURE_AD_TENANT_ID: {{ .Values.secrets.azureAdTenantId | quote }}
