{{- if and (not .Values.existingSecret.enabled) .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "nextjs-app.fullname" .) }}
  labels:
    {{- include "nextjs-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
