replicaCount: 2

image:
  repository: yourregistry.azurecr.io/next-auth-azure-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

secrets:
  azureAdClientId: "#{AZURE_AD_CLIENT_ID}#"
  azureAdClientSecret: "#{AZURE_AD_CLIENT_SECRET}#"
  azureAdTenantId: "#{AZURE_AD_TENANT_ID}#"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: yourdomain.example.com
      paths:
        - /
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
