replicaCount: 2

image:
  repository: your-registry/nextjs-app
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Secret configuration
secret:
  create: true
  name: nextjs-auth-secret
  data:
    AZURE_AD_CLIENT_ID: ""
    AZURE_AD_CLIENT_SECRET: ""

# For using existing secret
existingSecret:
  enabled: false
  name: ""

# Health probes
probes:
  liveness:
    path: /api/health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    path: /api/health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

ingress:
  enabled: true
  className: "nginx"
  name: ""  # Custom ingress name
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Force HTTPS
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # Forward as HTTP to backend service after TLS termination
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Timeout settings for Next.js
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    # Important header forwarding with TLS termination
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
  hosts:
    - host: nextjs-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextjs-app-tls
      hosts:
        - nextjs-app.example.com
